version: '3.9'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017" # Porta para acesso externo ao MongoDB
    environment:
      MONGO_INITDB_ROOT_USERNAME: root # Usuário administrador
      MONGO_INITDB_ROOT_PASSWORD: admin123 # Senha do usuário administrador
    volumes:
      - mongo-data:/data/db # Persistência de dados

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - "8081:8081" # Porta para acessar a interface web
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root # Usuário do MongoDB
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin123 # Senha do MongoDB
      ME_CONFIG_MONGODB_SERVER: mongodb # Nome do serviço MongoDB
    depends_on:
      - mongodb

volumes:
  mongo-data:
    driver: local

